### ISSUE TITLE
add assets to ACI

### ISSUE THREAD

**Issue by jonboulle** [appc/goaci#4]
It would be nice if `goaci` had a simple way to add assets to the rootfs of the produced ACI other than just the binary of the referenced go project. 

So for example, I could do something like `goaci github.com/example/mywebserver --assets /assets:/path/to/myassets` and the rootfs in the produced image would contain my website assets in `/assets`

(don't take this example as prescribed command line, I'm not sure on the best format; prior art elsewhere might provide better guidance)

**Comment by krnowak** [comment]
I implemented as described above, with the only difference in naming an option `--asset` instead of `--assets`. Also, this option can be used many times. Also, it is possible to use special placeholders - <GOPATH> and <PROJPATH>. The former is obvious, the latter is an absolute path to currently built project inside <GOPATH>. Thanks to this, user can add assets from the project it builds or from dependencies in GOPATH.
